##############################################################################
#
# ICT1002 Assignment 2, 2018-19 Trimester 2.
#
# You can use this file to build the ICT1002 Chatbot using make on Unix and
# MacOS X.
#
###############################################################################

chatmake: main.c chatbot.c knowledge.c utils.c
	mkdir ../bin
	gcc -o ../bin/chatbot main.c chatbot.c knowledge.c utils.c
